config/routes.rb
Rails.application.routes.draw do

  root 'data#index'
  get  'result',  to: 'data#result'
  get  'stat',    to: 'data#stat'
  post 'data',    to: 'data#data'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord

  #validation
  validates :number, uniqueness: {message: 'uniq number required'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  config.generators do |g|
    g.template_engine :slim
  end

end

app/controllers/data_controller.rb
class DataController < ApplicationController

  layout false

  http_basic_authenticate_with name: 'results', password: 'DuOWa5Ni' , except: [:index, :data]

  def index

    #render plain: 'all ok'

  end

  def data

    null = ''
    request.body.rewind
    result = JSON.parse request.body.read
    result = JSON.pretty_generate result
    result = JSON.parse result

    @result = Datum.new

    result.each do |key, value|

      if key == 'answer15'

        @result['name']   = value[0]
        @result['number'] = value[1]
        @result['lang']   = value[2]

      elsif key == 'get_params'
        @result[key] = value.truncate(128, omission: '')
      else

        @result[key] = value

      end

    end

    if @result.save
      render plain: 'ok'
    else
      render plain: @result.errors.first[1]
    end


  end

  def result

    @result = Datum.all

    #render format: [:html, :json]

    respond_to do |format|
      format.html
      format.json
      format.xls
    end

  end

  def stat
    # nothing
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper

  def single_value key, value

    if value.class == String

      value = value.split('"')
      result = ("\"#{key}\": \"#{value[1]}\"").html_safe

    elsif value.nil?

      result = ("\"#{key}\": \"\"").html_safe

    else

      result = ("\"#{key}\": \"#{value}\"").html_safe

    end

    result

  end

  def xls_single_value value

    result = ''

    unless value.nil?

      if value.class == String

        value = value.split('"')
        result = value[1].html_safe

      else

        result = value.html_safe

      end

    end

    result

  end


  def multi_value key, value

    if value.nil?

      result = ("\"#{key}\": \"\"").html_safe

    else

      value = value.gsub('[', '').gsub(']', '').split(', ')
      result = ''

      value.each_with_index do |v, i|

        unless v == 'nil' || v.nil?

          ( value.length - 1) == i ? result += "#{v.gsub('"', '')}" : result += "#{v.gsub('"', '')}, "

        end

        #puts result

      end

      result = ("\"#{key}\": \"#{result}\"").html_safe

    end

    result

  end

  def xls_multi_value value

    if value.nil?

      result = ''

    else

      value = value.gsub('[', '').gsub(']', '').split(', ')
      result = ''

      value.each_with_index do |v, i|

        unless v == 'nil' || v.nil?

          ( value.length - 1) == i ? result += "#{v.gsub('"', '')}" : result += "#{v.gsub('"', '')}, "

        end

        #puts result

      end

      result = result.html_safe

    end

    result

  end

  def formatted_value key , value

    ("\"#{key}\": \"#{value}\"").html_safe

  end

  def coma(index, result)

    (result - 1) == index ? '' : ','

  end

  def get_params_format value

    result = "\"get_params\": \"\""

    unless value.nil?

      result =  "\"get_params\": \"#{URI::decode(value)}\""

    end

    result.html_safe

  end

  def xls_get_params value

    result = ''

    unless value.nil?

      result =  URI::decode(value)

    end

    result.html_safe

  end

end

app/views/data/_counts.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-113447270-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-113447270-1');
</script>
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter47535211 = new Ya.Metrika({
          id:47535211,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true,
          webvisor:true
        });
      } catch(e) { }
    });
    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://mc.yandex.ru/metrika/watch.js";
    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/47535211" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<script>
  window._txq = window._txq || [];
  var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//st.targetix.net/txsp.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(s);
  _txq.push(['createPixel', '5aba4d447bc72f8b78ccc4ed']);
  _txq.push(['track', 'PageView']);
</script>

app/views/data/data.html.erb
<h1>Data#data</h1>
<p>Find me in app/views/data/data.html.erb</p>

app/views/data/result.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"
    = csrf_meta_tags
    = canonical_tag
    link rel="apple-touch-icon" sizes="180x180" href="/icon/apple-touch-icon.png"
    link rel="icon" type="image/png" sizes="32x32" href="/icon/favicon-32x32.png"
    link rel="icon" type="image/png" sizes="16x16" href="/icon/favicon-16x16.png"
    link rel="manifest" href="/icon/manifest.json"
    link rel="mask-icon" href="/icon/safari-pinned-tab.svg" color="#5bd1f2"
    meta name="theme-color" content="#ffffff"

    title Результаты опроса
    link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700&amp;subset=cyrillic" rel="stylesheet"
    link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.2/css/tabulator.min.css" rel="stylesheet"
    link rel="stylesheet" type="text/css" href="/assets/app.css"
    link rel="stylesheet" type="text/css" href="/assets/res.css"
    link rel="stylesheet" type="text/css" href="/assets/res_table.css"
  body
    header
      nav.black
        .nav-wrapper
          a href="/result" class="brand-logo" Результаты опроса
          ul class="right hide-on-med-and-down"
            li
              a href="/result" Таблица
            li
              a href="/stat" Статистика
      .panel
        = link_to 'Скачать таблицу', result_path(format: 'xls'), class: 'waves-effect waves-light btn'
    .table
      #result
    footer
    script src= "https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"
    script src= "https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin= "anonymous"
    script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.2/js/tabulator.min.js"
    script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"
    script type="text/javascript" src="/assets/jsonQ.min.js"
    script type="text/javascript" src="/assets/res.js"

app/views/data/result.json.erb
<%- result_length = @result.length %>
[
  <%- @result.each_with_index do |r, i|  %>
  {
    <%= single_value 'id', r.id %>,
    <%= single_value 'answer0', r.answer0 %>,
    <%= single_value 'answer1', r.answer1 %>,
    <%= single_value 'answer2', r.answer2 %>,
    <%= multi_value  'answer3', r.answer3 %>,
    <%= single_value 'answer4', r.answer4 %>,
    <%= multi_value  'answer5', r.answer5 %>,
    <%= single_value 'answer6', r.answer6 %>,
    <%= multi_value  'answer7', r.answer7 %>,
    <%= single_value 'answer8', r.answer8 %>,
    <%= single_value 'answer9', r.answer9 %>,
    <%= single_value 'answer10', r.answer10 %>,
    <%= single_value 'answer11', r.answer11 %>,
    <%= single_value 'answer12', r.answer12 %>,
    <%= single_value 'answer13', r.answer13 %>,
    <%= single_value 'answer14', r.answer14 %>,
    <%= formatted_value 'name', r.name %>,
    <%= formatted_value 'number', r.number %>,
    <%= formatted_value 'lang', r.lang %>,
    <%= formatted_value 'date', (r.created_at).strftime("%d.%m.%Y %H:%I") %>,
    <%= get_params_format r.get_params %>
  }<%= coma i, result_length %>
  <%- end %>
]

app/views/data/result.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row ss:AutoFitHeight="0">
        <Cell><Data ss:Type="String">№</Data></Cell>
        <Cell><Data ss:Type="String">Номер</Data></Cell>
        <Cell><Data ss:Type="String">Имя</Data></Cell>
        <Cell><Data ss:Type="String">Пол</Data></Cell>
        <Cell><Data ss:Type="String">Возраст</Data></Cell>
        <Cell><Data ss:Type="String">Как часто потребляет пиво</Data></Cell>
        <Cell><Data ss:Type="String">Марки пива</Data></Cell>
        <Cell><Data ss:Type="String">Помнит проект «Всё начинается с Кружки»</Data></Cell>
        <Cell><Data ss:Type="String">Откуда узнал о проекте</Data></Cell>
        <Cell><Data ss:Type="String">Прошёл регистрацию на сайте</Data></Cell>
        <Cell><Data ss:Type="String">Что побудило к участию</Data></Cell>
        <Cell><Data ss:Type="String">О чем было видео</Data></Cell>
        <Cell><Data ss:Type="String">С какой маркой ассоциируется проект «Всё начинается с Кружки»</Data></Cell>
        <Cell><Data ss:Type="String">Как понимает сообщение «Всё начинается с Кружки»</Data></Cell>
        <Cell><Data ss:Type="String">Почему не участвовал в конкурсе</Data></Cell>
        <Cell><Data ss:Type="String">Что можем сделать, чтобы участвовал в следующий раз</Data></Cell>
        <Cell><Data ss:Type="String">Какие виды призов</Data></Cell>
        <Cell><Data ss:Type="String">Какие условия участия привлекательны</Data></Cell>
        <Cell><Data ss:Type="String">Язык</Data></Cell>
        <Cell><Data ss:Type="String">Дата</Data></Cell>
        <Cell><Data ss:Type="String">Системная информация</Data></Cell>
      </Row>
      <%- @result.each_with_index do |r, i|  %>
      <Row ss:AutoFitHeight="0">
        <Cell><Data ss:Type="Number"><%= i + 1 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= r.number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= r.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer0 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer1 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer2 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_multi_value  r.answer3 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer4 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_multi_value  r.answer5 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer6 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_multi_value  r.answer7 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer8 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer9 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer10 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer11 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer12 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer13 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_single_value r.answer14 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= r.lang %></Data></Cell>
        <Cell><Data ss:Type="String"><%= r.created_at.strftime("%d.%m.%Y %H:%I") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= xls_get_params r.get_params %></Data></Cell>
      </Row>
      <%- end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/data/stat.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"
    = csrf_meta_tags
    = canonical_tag
    link rel="apple-touch-icon" sizes="180x180" href="/icon/apple-touch-icon.png"
    link rel="icon" type="image/png" sizes="32x32" href="/icon/favicon-32x32.png"
    link rel="icon" type="image/png" sizes="16x16" href="/icon/favicon-16x16.png"
    link rel="manifest" href="/icon/manifest.json"
    link rel="mask-icon" href="/icon/safari-pinned-tab.svg" color="#5bd1f2"
    meta name="theme-color" content="#ffffff"

    title Результаты опроса
    link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700&amp;subset=cyrillic" rel="stylesheet"
    link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.2/css/tabulator.min.css" rel="stylesheet"
    link rel="stylesheet" type="text/css" href="/assets/app.css"
    link rel="stylesheet" type="text/css" href="/assets/res.css"
    link rel="stylesheet" type="text/css" href="/assets/res_table.css"
  body
    header
      nav.black
        .nav-wrapper
          a href="/result" class="brand-logo" Результаты опроса
          ul class="right hide-on-med-and-down"
            li
              a href="/result" Таблица
            li
              a href="/stat" Статистика
      .panel
        = link_to 'Скачать таблицу', result_path(format: 'xls'), class: 'waves-effect waves-light btn'
    #stat.container
      .row
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#sex
            div.card-content
              span.card-title.grey-text.text-darken-4 Пол участников Рекламной кампании
              p
                | Мужчины:&nbsp;
                span#sex0
                br
                | Женщины:&nbsp;
                span#sex1
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#lang
            div.card-content
              span.card-title.grey-text.text-darken-4 Язык участников Рекламной кампании
              p
                | Русский:&nbsp;
                span#lang0
                br
                | Казахский:&nbsp;
                span#lang1
      .row
        .col.s12.m12.l4
          div.card
            div.card-image
              canvas#age
            div.card-content
              span.card-title.grey-text.text-darken-4 Возраст участников
              p
                | 21-24:&nbsp;
                span#age0
                br
                | 25-29:&nbsp;
                span#age1
                br
                | 30-34:&nbsp;
                span#age2
                br
                | 35-40:&nbsp;
                span#age3
                br
        .col.s12.m6.l4
          div.card
            div.card-image
              canvas#rem
            div.card-content
              span.card-title.grey-text.text-darken-4 Помнит проект «Всё начинается с Кружки»
              p
                | Да:&nbsp;
                span#rem0
                br
                | Нет:&nbsp;
                span#rem1
        .col.s12.m6.l4
          div.card
            div.card-image
              canvas#reg
            div.card-content
              span.card-title.grey-text.text-darken-4 Регистрация на сайте
              p
                | Да:&nbsp;
                span#reg0
                br
                | Нет:&nbsp;
                span#reg1
      .row
        .col.s12
          div.card
            div.card-image
              canvas#beer
            div.card-content
              span.card-title.grey-text.text-darken-4 Марки пива
              p#beer0
      .row
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#known
            div.card-content
              span.card-title.grey-text.text-darken-4 Откуда узнал о проекте
              p#known0
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#reasons
            div.card-content
              span.card-title.grey-text.text-darken-4 Что побудило к участию
              p#reasons0
      .row
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#about
            div.card-content
              span.card-title.grey-text.text-darken-4 О чем было видео
              p#about0
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#association
            div.card-content
              span.card-title.grey-text.text-darken-4 С какой маркой ассоциируется проект «Всё начинается с Кружки»
              p#association0
      .row
        .col.s12
          div.card
            div.card-image
              canvas#understand
            div.card-content
              span.card-title.grey-text.text-darken-4 С какой маркой ассоциируется проект «Всё начинается с Кружки»
              p#understand0
      .row
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#why
            div.card-content
              span.card-title.grey-text.text-darken-4 Почему не участвовал в конкурсе
              p#why0
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#next
            div.card-content
              span.card-title.grey-text.text-darken-4 Что можем сделать, чтобы участвовал в следующий раз?
              p#next0
      .row
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#prizes
            div.card-content
              span.card-title.grey-text.text-darken-4 Какие виды призов
              p#prizes0
        .col.s12.m6.l6
          div.card
            div.card-image
              canvas#rules
            div.card-content
              span.card-title.grey-text.text-darken-4 Какие условия участия привлекательны
              p#rules0
    footer
    script src= "https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"
    script src= "https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin= "anonymous"
    script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.2/js/tabulator.min.js"
    script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"
    script type="text/javascript" src="/assets/jsonQ.min.js"
    script type="text/javascript" src="/assets/res.js"